services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ksu-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      TZ: Asia/Jakarta
    ports:
      - "3000:3000"
    volumes:
      # Mount backup directory untuk backup files
      - ./backups:/app/backups
      # Mount logs directory
      - ./logs:/app/logs
      # Mount timezone info
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
