version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ksu-backend
    restart: unless-stopped
    environment:
      DATABASE_URL_NEW: mysql://root:Ksu123321@@192.168.99.2:3306/ksu?allowPublicKeyRetrieval=true
      JWT_SECRET_KEY: ksu_koperasi
      NODE_ENV: production
    ports:
      - "3000:3000"
