version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ksu-backend
    restart: always
    environment:
      DATABASE_URL_BARU: mysql://root:Ksu123321@@192.168.137.2:3306/ksu?allowPublicKeyRetrieval=true
      JWT_SECRET_KEY: ksu_koperasi
      NODE_ENV: production
    ports:
      - "3000:3000"
