version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ksu-backend
    restart: always
    environment:
      DATABASE_URL_BARU: mysql://root:Ksu123321@@localhost:3306/ksu
      JWT_SECRET_KEY: ksu_koperasi
      NODE_ENV: production
    ports:
      - "3000:3000"
