import express from "express";
import { authMiddleware } from "../middleware/auth-middleware.js";
import cashInOutRoute from "./routes/cash-in-out-route.js";
import anggotaRoute from "./routes/anggota-route.js";
import productRoute from "./routes/product-route.js";
import roleRoute from "./routes/role-route.js";
import userRoute from "./routes/user-route.js";
import purchaseRoute from "./routes/purchase-route.js";
import supplierRoute from "./routes/supplier-route.js";
import divisiRoute from "./routes/divisi-route.js";
import saleRoute from "./routes/sale-route.js";
import stockTakeRoute from "./routes/stock-take-route.js";
import dashboardRoute from "./routes/dashboard-route.js";
import laporanRoute from "./routes/laporan-route.js";
import returRoute from "./routes/retur-route.js";
import tutupKasirRoute from "./routes/tutup-kasir-route.js";
import hutangAnggotaRoute from "./routes/hutang-anggota.route.js";
import hutangDagangRoute from "./routes/hutang-dagang.route.js";

const userRouter = new express.Router();
userRouter.use(authMiddleware);

userRoute();
roleRoute();
divisiRoute();
supplierRoute();
productRoute();
anggotaRoute();
cashInOutRoute();
purchaseRoute();
saleRoute();
stockTakeRoute();
dashboardRoute();
laporanRoute();
returRoute();
tutupKasirRoute();
hutangAnggotaRoute();
hutangDagangRoute();

export { userRouter };
