const CASH_OUT_CODES = {
  PENARIKAN_DARI_BRI: 1,
  PENARIKAN_DARI_BNI: 2,
  TENANT: 3,
  PENDAPATAN_LAIN_LAIN: 4,
  BEBAN_GAJI: 5,
  UANG_MAKAN_KARYAWAN: 6,
  THR_KARYAWAN: 7,
  BEBAN_ADM_UMUM: 8,
  BEBAN_PERLENGKAPAN: 9,
  PEMELIHARAAN_INVENTARIS: 10,
  PEMELIHARAAN_GEDUNG: 11,
  TAGIHAN_LISTRIK: 12,
  HONOR_PENGAWAS: 13,
  HONOR_PENGURUS: 14,
  LAIN_LAIN: 15,
  TRANSFER_KE_BRI: 16,
  TRANSFER_KE_BNI: 17,
  PEMBAYARAN_HUTANG_PIHAK_KETIGA: 18,
  HUTANG_PIHAK_KETIGA: 19,
};

export { CASH_OUT_CODES };
