-- AlterTable
ALTER TABLE `divisi` ADD COLUMN `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN `updated_at` TIMESTAMP(6) NULL;

-- AlterTable
ALTER TABLE `roles` ADD COLUMN `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN `updated_at` TIMESTAMP(6) NULL;
